name: Build and Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

        steps:
          - name: Checkout 🛎️
            uses: actions/checkout@v2
            # If you're using actions/checkout@v2 you must set
            # persist-credentials to be false in most cases
            with:
              persist-credentials: false

          - name: Install, Build, and Export
            uses: actions/setup-node@v1
          - run: npm install
          - run: npm run build

          - name: Deploy
            uses: JamesIves/github-pages-deploy-action@3.6.2
            with:
              GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}}
              BRANCH: prod # The branch the action should deploy to
              FOLDER: src/out # The folder the action should deploy
              CLEAN: true # Automatically remove delted files from the deployment branch
